
# Health
# health_check_interval: 60
# target_app_health_check_path: "/ats/ess-public-covid/v1"
# unhealthy_threshold_count: 5


# target_desired_task_count: 2
target_app_context: "/salesforce-person-updates"
target_app_version: "v1.0.5"
create_service: false

# this is the lowest for fargate?
# target_memory_mb: 1024
# target_cpu: 256
target_memory_mb: 2048
target_cpu: 1024

# target_port: 9201
target_app_name: "salesforce-person-updates"
# target_app_hostname: "person-api"
# target_app_zone: "dev.ats.cloud.huit.harvard.edu"

target_container_image: "artifactory.huit.harvard.edu/aais-docker-local/salesforce-person-updates"

target_container_credentials: "arn:aws:secretsmanager:us-east-1:949726781110:secret:aais-services-prod-artifactory-creds-BVDDOX"
target_container_host: "artifactory.huit.harvard.edu:443"
use_cache: true

target_launchtype: "FARGATE"
target_alb_name: "def"

# target_app_secrets_ref:
#   - aais-: "arn:aws:secretsmanager:us-east-1:001980101248:secret:aais-services-oakdev-mule-oOJhHY:password::"
#     aais-elastic: "arn:aws:secretsmanager:us-east-1:001980101248:secret:aais-services-elastic-dev-SfyZ3Z:password::"

schedules:

    ####### HUIT Prod ####################################################################
    # required
    # Note: the full schedule name can only be 64 characters long
  - schedule_rule_name: "huit-updates" # this will be appended to the task definition name, e.g my-cluster-dev-feed-my-dataload-half-hourly
    schedule_expression: "rate(30 minutes)" # rate or cron expression
    # optional
    schedule_rule_description: "Updates for the HUIT prod instance (huit-prod)"
    # environment variable overrides
    schedule_env_overrides:
      - name: "TABLE_NAME"
        value: "aais-services-salesforce-person-updates-prod"
      - name: "SALESFORCE_INSTANCE_ID"
        value: "huit-prod"
      - name: "action"
        value: "person-updates"

    ####### HMS Prod ####################################################################
  - schedule_rule_name: "hms-updates" # this will be appended to the task definition name, e.g my-cluster-dev-feed-my-dataload-half-hourly
    schedule_expression: "rate(15 minutes)" # rate or cron expression
    # optional
    schedule_rule_description: "Updates for the HMS prod. (hms-prod)"
    # environment variable overrides
    schedule_env_overrides:
      - name: "TABLE_NAME"
        value: "aais-services-salesforce-person-updates-prod"
      - name: "SALESFORCE_INSTANCE_ID"
        value: "hms-prod"
      - name: "action"
        value: "person-updates"
    # schedule_rule_state: "DISABLED"

    ####### HKS Prod ####################################################################
  - schedule_rule_name: "hks-updates" # this will be appended to the task definition name, e.g my-cluster-dev-feed-my-dataload-half-hourly
    schedule_expression: "rate(15 minutes)" # rate or cron expression
    # optional
    schedule_rule_description: "Updates for the HKS prod"
    # environment variable overrides
    schedule_env_overrides:
      - name: "TABLE_NAME"
        value: "aais-services-salesforce-person-updates-prod"
      - name: "SALESFORCE_INSTANCE_ID"
        value: "hks-prod"
      - name: "action"
        value: "person-updates"

    ####### CS Prod ####################################################################
  - schedule_rule_name: "cs-updates" # this will be appended to the task definition name, e.g my-cluster-dev-feed-my-dataload-half-hourly
    schedule_expression: "rate(30 minutes)" # rate or cron expression
    # optional
    schedule_rule_description: "Updates for the Campus Services (CS) Prod. (cs-prod)"
    # environment variable overrides
    schedule_env_overrides:
      - name: "TABLE_NAME"
        value: "aais-services-salesforce-person-updates-prod"
      - name: "SALESFORCE_INSTANCE_ID"
        value: "cs-prod"
      - name: "action"
        value: "person-updates"
