name: "Get Instances"
description: "Action to get all Salesforce instances from DynamoDB"
inputs:
  table_name:
    type: string
    required: true
  region: 
    type: string
    required: false
    default: "us-east-1"
outputs:
  instances:
    description: "Array of instance ids"
    value: ${{ steps.run-action.outputs.instances }}

runs:
  using: "composite"
  steps:

    - name: "Install python"
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        
    - name: Create virtual env and activate
      run: |
        python3 -m venv build-env
        source build-env/bin/activate
      shell: bash

    - name: Requirements
      run: |
        source build-env/bin/activate
        python3 -m pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: "Run action script"
      id: "run-action"
      run: |
        source build-env/bin/activate
        python ${{ github.action_path }}/action.py "${{ inputs.table_name }}" > instances.json
        echo "instances=$(cat instances.json)">> $GITHUB_OUTPUT
        rm instances.json
      shell: "bash"
      env:
        AWS_REGION: ${{ inputs.region }}