name: Build Image
run-name: Build Image ${{ github.event.inputs.version }}

on:
  push:
    branches: [ dev ]
    paths: 
        - 'src/**'
        - 'config.schema.json'
        - 'Dockerfile'
        - 'gunicorn.sh'
        - 'requirements.txt'
        - '.github/workflows/build.yml'
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

env:
  version: ${{ github.event.inputs.version }}
  branch: ${{ github.ref_name }}

defaults:
  run:
    shell: bash

jobs:
  unittest:
    name: Running Unit tests
    runs-on: ubuntu-latest
    container:
      image: python:3.9
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # with: 
        #   path: ./salesforce

      - name: Create virtual env
        run: |
          python -m venv env

      - name: Get requirements
        run: |
          source env/bin/activate
          python -m pip config --cache-dir env set global.extra-index-url https://artifactory.huit.harvard.edu/artifactory/api/pypi/ats-python/simple
          python -m pip install -r src/requirements.txt

      - name: Run tests
        run: | 
          source env/bin/activate
          python -m unittest discover -s src -p *_test.py    

  # get_version:
  #   name: Get Version
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout the code
  #       uses: actions/checkout@v3
  #       with: 
  #         path: ./checkout
  #     - name: Run the action
  #       id: get_version
  #       uses: HUIT/aais-ecs-infrastructure/actions/get-version@develop
  #       with:
  #         ansible_vars: ./checkout/ansible_vars/dev_ansible_vars.yml
  #   outputs:
  #     version: ${{ steps.get_version.outputs.version }}

  versions:
    name: Get all Deployed Versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with: 
          path: ./checkout
      - name: Get Dev Version
        id: get_dev_version
        uses: HUIT/aais-ecs-infrastructure/actions/get-version@develop
        with:
          ansible_vars: ./checkout/ansible_vars/dev_ansible_vars.yml
      - name: Get Test Version
        if: inputs.version != null
        id: get_test_version
        uses: HUIT/aais-ecs-infrastructure/actions/get-version@develop
        with:
          ansible_vars: ./checkout/ansible_vars/test_ansible_vars.yml
      - name: Get Stage Version
        if: inputs.version != null
        id: get_stage_version
        uses: HUIT/aais-ecs-infrastructure/actions/get-version@develop
        with:
          ansible_vars: ./checkout/ansible_vars/stage_ansible_vars.yml
      - name: Get Prod Version
        if: inputs.version != null
        id: get_prod_version
        uses: HUIT/aais-ecs-infrastructure/actions/get-version@develop
        with:
          ansible_vars: ./checkout/ansible_vars/prod_ansible_vars.yml

      - name: JSON Output
        id: json_output
        if: inputs.version != null
        run: |
          python - <<EOF
          import json
          cache_updates = []
          if "${{ inputs.version }}" == "${{ steps.get_dev_version.outputs.version }}":
            cache_updates.append({"env": "dev", "version": "${{ steps.get_dev_version.outputs.version }}"})
          if "${{ inputs.version }}" == ${{ steps.get_test_version.outputs.version }}:
            cache_updates.append({"env": "test", "version": "${{ steps.get_test_version.outputs.version }}"})
          if "${{ inputs.version }}" == ${{ steps.get_stage_version.outputs.version }}:
            cache_updates.append({"env": "stage", "version": "${{ steps.get_stage_version.outputs.version }}"})
          if "${{ inputs.version }}" == "${{ steps.get_prod_version.outputs.version }}":
            cache_updates.append({"env": "prod", "version": "${{ steps.get_prod_version.outputs.version }}"})
          print(json.dumps(cache_updates))
          EOF >> $GITHUB_OUTPUT
    outputs:
      dev: ${{ steps.get_dev_version.outputs.version }}
      cache_updates: ${{ steps.json_output.outputs }}

  build:
    name: Build Code ${{ inputs.version }}
    needs: [unittest, versions]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          path: ./checkout

      - name: Which Version
        id: which_version
        run: |
          if [ -z "${{ inputs.version }}" ]; then
            echo "Version from dev_ansible_vars: ${{ needs.versions.outputs.dev }}"
            echo "version=${{ needs.versions.outputs.dev }}" >> $GITHUB_OUTPUT
          else
            echo "Version from input: ${{ inputs.version }}"
            echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
          fi
      - name: Build
        run: |
          cd checkout
          docker build -t artifactory.huit.harvard.edu/aais-docker-local/salesforce-person-updates:${{ steps.which_version.outputs.version }} .

      - name: Push to Artifactory
        run: |
          docker login artifactory.huit.harvard.edu --username "${{ secrets.ARTIFACTORY_USER }}" --password "${{ secrets.ARTIFACTORY_PWD }}"
          docker push artifactory.huit.harvard.edu/aais-docker-local/salesforce-person-updates:${{ steps.which_version.outputs.version }}


  deploy:
    name: Deploy to Dev
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    needs: [versions, build]
    uses: ./.github/workflows/deploy.yml
    with: 
      version: ${{ needs.versions.outputs.dev }}
      environment: dev
    secrets: inherit

  cache_deploys:
    name: Cache Deploys
    needs: [versions, build]
    strategy:
      matrix:
        versions: ${{ needs.versions.outputs.cache_updates }}
    uses: ./.github/workflows/deploy.yml
    with: 
      version: ${{ matrix.versions.version }}
      environment: ${{ matrix.versions.env }}
    secrets: inherit
