name: Check Salesforce Instances
run-name: Check all Salesforce Instances on ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        options: 
            - 'dev'
            - 'test'
            - 'stage'
            - 'prod'

defaults:
  run:
    shell: bash

jobs:
  get_instances:
    name: Get all Instances for ${{ inputs.environment }}
    runs-on: arc-runner-set-huit
    # runs-on: ubuntu-latest
    container:
      image: amazonlinux:latest
      options: --user root
    environment: ${{ inputs.environment }}
    steps:
      - name: Login to AWS with a service account / iam user
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NONPROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NONPROD }}
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: 'arn:aws:iam::${{ vars.AWS_ACCOUNT }}:role/AutomationDeployRole'
          role-duration-seconds: 1200
          role-session-name: MyDeploySession
          role-skip-session-tagging: true
          role-external-id: ${{ secrets.EXTERNAL_ID }}
    
      - name: Install AWS CLI
        run: |
          yum install -y aws-cli
          aws --version

      - name: Get All Instance Ids
        id: get-instances
        env:
          TABLE_NAME: ${{ vars.TABLE_NAME }}
        run: |
          echo "## Instances" >> $GITHUB_STEP_SUMMARY
          echo "on table: $TABLE_NAME" >> $GITHUB_STEP_SUMMARY
          ids=$(aws dynamodb scan --table-name $TABLE_NAME --query "Items[*].id.S")
          echo "$ids" >> $GITHUB_STEP_SUMMARY

          # remove newlines from $ids string
          instances=$(echo $ids | tr -d '\n')

          echo "$instances" >> $GITHUB_STEP_SUMMARY

          # this isn't enough, we need to escaoe the double quotes?
          echo "instances=$instances">> "$GITHUB_OUTPUT"

    outputs:
      instances: ${{ steps.get-instances.outputs.instances }}
          

  check_instances:
    name: Check Instances
    if: needs.get_instances.outputs.instances != '[]'
    needs: [ get_instances ]
    strategy:
      # max-parallel: 2
      fail-fast: false
      matrix:
        # instance: [ instance1 ]
        instance: ${{ fromJson(needs.get_instances.outputs.instances) || '[]' }}
    uses: ./.github/workflows/run_action.yml
    with: 
      environment: ${{ inputs.environment }}
      salesforce_instance_id: ${{ matrix.instance }}
      action: 'test'
      debug: 'False'
    secrets: inherit
