name: Check Credentials
run-name: Build Image ${{ inputs.environment }}

on:
  push:
    branches: [ dev ]
    paths: 
        - 'src/**'
        - 'config.schema.json'
        - 'Dockerfile'
        - 'gunicorn.sh'
        - 'requirements.txt'
        - '.github/workflows/build.yml'
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        options: 
            - 'dev'
            - 'test'
            - 'stage'
            - 'prod'

defaults:
  run:
    shell: bash

jobs:
  get_instances:
    name: Get all Instances for ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with: 
          path: ./checkout
      - name: Get Instances Python
        id: get-instances
        uses: ./checkout/.github/actions/get_instances
        with:
          table_name: ${{ vars.TABLE_NAME }}
    outputs:
      instances: ${{ steps.get-instances.outputs.instances }}

  check_instances:
    name: Check Instances
    if: needs.get_instances.outputs.instances != '[]'
    needs: get_instances
    strategy:
      fail-fast: false
      matrix:
        instance: ${{ fromJson(needs.get_instances.outputs.instances) || '[]' }}
    uses: ./checkout/.github/workflows/run_action.yml
    with: 
      environment: ${{ inputs.environment }}
      salesforce_instance_id: ${{ matrix.instance }}
      action: 'test'
      debug: 'False'
    secrets: inherit
