name: Deploy Task Definition
run-name: Deploying ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }}

on:
  # push:
  #   branches: [ dev ]
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
      environment:
        type: choice
        default: 'dev'
        options: 
          - 'dev'
          - 'test'
          - 'stage'
          - 'prod'
        required: true
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      environment:
        type: string
        required: true

env:
  AWS_REGION: us-east-1

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest

    steps:

      - name: Login to AWS with a service account / iam user
        uses: HUIT/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NONPROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NONPROD }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./checkout
          
      - name: Run AAIS Deploy Container Action
        uses: HUIT/aais-ecs-infrastructure/actions/deploy-container@develop
        with:
          # Required
          ansible_vars: ansible_vars/${{ inputs.environment }}_ansible_vars.yml
          cluster_config_repository: HUIT/aais-services-config
          cluster_config: aais_services_${{ inputs.environment }}.yml
          # Required -- this token is linked to the user associated with the run
          github_token: ${{ github.token }}
          # Optional
          #   this needs to match the directory the main repository was checked out into
          #   if the checkout was done without a path, this is not needed
          app_root: checkout
          infrastructure_branch: develop
          debug: true
     