name: Postman Testing
on:
  workflow_dispatch:
  push:

defaults:
  run:
    shell: bash

jobs:
  unittest:
    name: Running Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get requirements
        run: pip install -r src/requirements.txt

      - name: Run tests
        run: | 
          cd src
          python -m unittest tests
