name: Unit Tests
on:
  workflow_dispatch:
  push:

defaults:
  run:
    shell: bash

jobs:
  unittest:
    name: Running Unit tests
    runs-on: ubuntu-latest
    container:
      image: python:3.9
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create virtual env and activate
        run: |
          python -m venv env

      - name: Get requirements
        run: |
          source env/bin/activate
          python -m pip install -r src/requirements.txt
          

      - name: Run tests
        run: | 
          source env/bin/activate
          python -m unittest discover -s src -p *_test.py