name: Spot Data Update

on:
  workflow_dispatch:
    inputs:
      environment: 
        type: choice
        default: 'dev'
        options:
          - 'dev'
          - 'test'
          - 'stage'
          - 'prod'
        required: true
      people:
        description: HUIDs (comma separated list?) 
        type: string
        required: true
        default: '<HUID>, <HUID>, <HUID>'
      salesforce_instance_id:
        description: the salesforce instance id (from dynamo)
        type: string
        required: true
        default: 'huit-full-sandbox'
      task_version:
        type: string
        required: false
        default: ''
        
        

env:
  AWS_REGION: us-east-1


defaults:
  run:
    shell: bash

jobs:
  data_load: 
    name: Spot data update on ${{ github.event.inputs.environment }} for ${{ github.event.inputs.people }} on ${{ github.event.inputs.salesforce_instance_id }}
    runs-on: [ ubuntu-latest ]

    steps:
    #   - name: test task_version value
    #     run: |
    #       echo "\"${{ github.event.inputs.task_version }}\""

    #   - name: Set task version format
    #     if: ${{ github.event.inputs.task_version != '' }}
    #     run: |
    #       echo "task_version=:${{ github.event.inputs.task_version }}" >> $GITHUB_ENV

      - name: Set admints-dev environment vars
        if: ${{ github.event.inputs.environment == 'dev' || github.event.inputs.environment == 'test' }}
        run: |
          echo "account=001980101248" >> $GITHUB_ENV
          echo "account_name=admintsdev" >> $GITHUB_ENV
          echo "security_group=sg-07d8897b8146667d1" >> $GITHUB_ENV
          echo "subnet=subnet-b1d4cac7" >> $GITHUB_ENV
          echo "TABLE_NAME=aais-services-salesforce-person-updates-dev" >> $GITHUB_ENV

      - name: Set admints environment vars
        if: ${{ github.event.inputs.environment == 'stage' || github.event.inputs.environment == 'prod' }}
        run: |
          echo "account=949726781110" >> $GITHUB_ENV
          echo "account_name=admints" >> $GITHUB_ENV
          echo "security_group=sg-0d4440255bb6c7b71" >> $GITHUB_ENV
          echo "subnet=subnet-152e3063" >> $GITHUB_ENV
          echo "TABLE_NAME=aais-services-salesforce-person-updates-prod" >> $GITHUB_ENV


      - name: Login to AWS with a service account / iam user
        uses: HUIT/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NONPROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NONPROD }}
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: 'arn:aws:iam::${{ env.account }}:role/AutomationDeployRole'
          role-duration-seconds: 1200
          role-session-name: MyDeploySession
          role-skip-session-tagging: true
          role-external-id: ${{ secrets.EXTERNAL_ID }}

      - name: get current identity
        run: aws sts get-caller-identity

      - name: Create Overrides
        run: |
          CONTAINER_OVERRIDES='[ 
            {
              "name": "aais-services-${{ github.event.inputs.environment }}-feed-salesforce-person-updates", 
              "environment": [ 
                {
                  "name": "SALESFORCE_INSTANCE_ID", 
                  "value": "${{ github.event.inputs.salesforce_instance_id }}"
                }, {
                  "name": "TABLE_NAME", 
                  "value": "${{ env.TABLE_NAME }}"
                }, {
                  "name": "action", 
                  "value": "single-person-update"
                }, {
                  "name": "person_ids", 
                  "value": "[${{ github.event.inputs.people }}]"
                }
              ]
            } 
          ]'
          CONTAINER_OVERRIDES=$(echo "$CONTAINER_OVERRIDES" | tr -d '\n')
          echo "CONTAINER_OVERRIDES=$CONTAINER_OVERRIDES" >> $GITHUB_ENV

      - name: Run ${{ github.event.inputs.environment }} spot update on [${{ github.event.inputs.people }}]
        run: |
          aws ecs run-task \
            --cluster aais-services-${{ github.event.inputs.environment }}-cluster \
            --overrides '{"containerOverrides": ${{ env.CONTAINER_OVERRIDES }} }' \
            --task-definition arn:aws:ecs:us-east-1:${{ env.account }}:task-definition/aais-services-${{ github.event.inputs.environment }}-feed-salesforce-person-updates${{ env.task_version }} \
            --network-configuration '{ "awsvpcConfiguration": { "assignPublicIp":"DISABLED", "securityGroups": ["${{ env.security_group }}"], "subnets": ["${{ env.subnet }}"]}}' \
            --launch-type FARGATE

        # Above Command without vars
        # aws ecs run-task \
        #   --cluster aais-ecs-dev-cluster \
        #   --overrides '{"containerOverrides": [ {"name": "aais-ecs-dev-feed-salesforce-person-updates", "environment": [ {"name": "action", "value": "full"} ] } ] }' \
        #   --task-definition arn:aws:ecs:us-east-1:001980101248:task-definition/aais-ecs-dev-feed-salesforce-person-updates:99